### ISSUE TITLE
ESP32 NodeMCU as primary ambilight device

### ISSUE THREAD

**Issue by LichtiMC** [SciLor/Hyperion_LED-Controller#60] opened 2020-08-02 22:58 UTC
On the README site it says "... 2 instances of hyperion necessary ... first one controls local ambilight and forwards data to the second instance, which then sends data to the Hyperion_LED-Controller..."

My question: Do you know any reasons for not using the ESP32-solution as primary (and only) ambilight?
Is there a significantly larger delay or some other downsites of the transmission of data over the network?

If not, I guess this would be a more flexible way regarding the media-player-location... (I would not need an additional cable from tv to media-player)

Thanks

**Comment by SciLor** [comment] 2020-08-03 04:20
Duplicate of https://github.com/SciLor/Hyperion_LED-Controller/issues/42

**Closed as completed by SciLor** 2020-08-03 04:20 UTC
Labels: question
